### ISSUE TITLE
deploy-container-registry error on deploying the sample deployment via Deploy To Azure

### ISSUE THREAD

**Issue by kristopherjturner** [Azure/video-analyzer#47]
I have tried a few times but I keep having an error when it tries to deploy the container registry on the sample deployment solution.  

> The registry DNS name avasampleregistrysxn3dqx3nhjli.azurecr.io is already in use. You can check if the name is already claimed using following API: https://docs.microsoft.com/en-us/rest/api/containerregistry/registries/checknameavailability"

It looks to me that the randomization of the ACR name isn't working?

**Comment by jasonxian-msft** [comment]
Hi Kris, to deploy these resources, are you running the ARM template found here? 

https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/get-started-detect-motion-emit-events#set-up-azure-resources

If so, the template appends a unique string to each ACR resource based on the name of the resource group. If you keep getting the same used name, could you try forming a new resource group and see if that fixes the issue? Otherwise, we can point you to how to deploy your own ACR with the settings we specified in the ARM template.

**Comment by anilmur** [comment]
@kristopherjturner  - can this be closed?
